#
# Copyright Pravega Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

app: pravega-grpc-gateway
image:
  repository: pravega-grpc-gateway
  tag: 0.7.0
pravega:
  # Use below for SDP without TLS.
  controller: "tcp://nautilus-pravega-controller.nautilus-pravega.svc.cluster.local:9090"
  # Use below format for SDP with TLS.
  #controller: "tls://pravega-controller.cluster1.example.com:443"
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "pravega-grpc-gateway.examples.frightful-four.eaglemonk.intranet.nautilus-platform-dev.com"
  type: LoadBalancer
